### ISSUE TITLE
Make a new component from the select options

### ISSUE THREAD

**Issue by mariastlouis** [mariastlouis/headcount#48]

**Comment by mariastlouis** [comment]
Right now the options are in their own variable up top on the control button component. They should probably be their own component.

**Comment by katiescruggs** [comment]
I actually got rid of that component and just had the options as elements inside the DataSetSelect component. I thought this was cleaner, but let me know what you think! I still think we should probably make a header component that contains the h1, the p tag telling the user to select a data set, and the DataSetSelect component itself. Right now those are all hanging out in App. If we create a header component, we'll have to create tests for it too.
